services:
  app:
    image: ghcr.io/astral-sh/uv:python3.12-bookworm-slim # ghcr.io/astral-sh/uv:latest # docker.io/python:3.12-slim
    command: "uv sync && uvicorn main:app --host 0.0.0.0 --port 8000"
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PATH=/app/.venv/bin:$PATH
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: